import { lazy } from 'react';

import 'server-only';

import { Components } from '@/vibes/schema';

export const examples = [
  {
    name: 'checkbox-example',
    dependencies: [],
    registryDependencies: ['checkbox'],
    files: ['examples/form/checkbox/index.tsx'],
    component: lazy(() => import('./examples/form/checkbox')),
  },
  {
    name: 'checkbox-group-example',
    dependencies: [],
    registryDependencies: ['checkbox-group'],
    files: ['examples/form/checkbox-group/index.tsx'],
    component: lazy(() => import('./examples/form/checkbox-group')),
  },
  {
    name: 'compare-card-electric',
    dependencies: [],
    registryDependencies: ['compare-card-electric'],
    files: ['examples/primitives/compare-card/electric.tsx'],
    component: lazy(() => import('./examples/primitives/compare-card/electric')),
  },
  {
    name: 'compare-card-warm',
    dependencies: [],
    registryDependencies: ['compare-card-warm'],
    files: ['examples/primitives/compare-card/warm.tsx'],
    component: lazy(() => import('./examples/primitives/compare-card/warm')),
  },
  {
    name: 'compare-card-luxury',
    dependencies: [],
    registryDependencies: ['compare-card-luxury'],
    files: ['examples/primitives/compare-card/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/compare-card/luxury')),
  },
  {
    name: 'compare-drawer-electric',
    dependencies: [],
    registryDependencies: ['compare-drawer-electric'],
    files: ['examples/primitives/compare-drawer/electric.tsx'],
    component: lazy(() => import('./examples/primitives/compare-drawer/electric')),
  },
  {
    name: 'compare-drawer-warm',
    dependencies: [],
    registryDependencies: ['compare-drawer-warm'],
    files: ['examples/primitives/compare-drawer/warm.tsx'],
    component: lazy(() => import('./examples/primitives/compare-drawer/warm')),
  },
  {
    name: 'compare-drawer-luxury',
    dependencies: [],
    registryDependencies: ['compare-drawer-luxury'],
    files: ['examples/primitives/compare-drawer/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/compare-drawer/luxury')),
  },
  {
    name: 'accordion-example',
    dependencies: [],
    registryDependencies: ['accordion'],
    files: ['examples/primitives/accordion/index.tsx'],
    component: lazy(() => import('./examples/primitives/accordion')),
  },
  {
    name: 'account-settings-example',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/account-settings/index.tsx'],
    component: lazy(() => import('./examples/sections/account-settings')),
  },
  {
    name: 'address-list-section-example',
    dependencies: [],
    registryDependencies: [],
    files: [
      'examples/sections/address-list-section/index.tsx',
      'examples/sections/address-list-section/action.ts',
    ],
    component: lazy(() => import('./examples/sections/address-list-section')),
  },
  {
    name: 'alert-example',
    dependencies: [],
    registryDependencies: ['alert'],
    files: ['examples/primitives/alert/index.tsx'],
    component: lazy(() => import('./examples/primitives/alert')),
  },
  {
    name: 'animated-link-example',
    dependencies: [],
    registryDependencies: ['animated-link'],
    files: ['examples/primitives/animated-link/index.tsx'],
    component: lazy(() => import('./examples/primitives/animated-link')),
  },
  {
    name: 'banner-example',
    dependencies: [],
    registryDependencies: ['banner'],
    files: ['examples/primitives/banner/index.tsx'],
    component: lazy(() => import('./examples/primitives/banner')),
  },
  {
    name: 'badge-example',
    dependencies: [],
    registryDependencies: ['badge'],
    files: ['examples/primitives/badge/index.tsx'],
    component: lazy(() => import('./examples/primitives/badge')),
  },
  {
    name: 'blog-post-card-warm',
    dependencies: [],
    registryDependencies: ['blog-post-card'],
    files: ['examples/primitives/blog-post-card/warm.tsx'],
    component: lazy(() => import('./examples/primitives/blog-post-card/warm')),
  },
  {
    name: 'blog-post-card-electric',
    dependencies: [],
    registryDependencies: ['blog-post-card'],
    files: ['examples/primitives/blog-post-card/electric.tsx'],
    component: lazy(() => import('./examples/primitives/blog-post-card/electric')),
  },
  {
    name: 'blog-post-card-luxury',
    dependencies: [],
    registryDependencies: ['blog-post-card'],
    files: ['examples/primitives/blog-post-card/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/blog-post-card/luxury')),
  },
  {
    name: 'blog-post-content-example',
    dependencies: [],
    registryDependencies: ['blog-post-content'],
    files: ['examples/sections/blog-post-content/index.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-content')),
  },
  {
    name: 'blog-post-list-example-warm',
    dependencies: [],
    registryDependencies: ['blog-post-list'],
    files: ['examples/sections/blog-post-list/warm.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-list/warm')),
  },
  {
    name: 'blog-post-list-example-electric',
    dependencies: [],
    registryDependencies: ['blog-post-list'],
    files: ['examples/sections/blog-post-list/electric.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-list/electric')),
  },
  {
    name: 'blog-post-list-example-luxury',
    dependencies: [],
    registryDependencies: ['blog-post-list'],
    files: ['examples/sections/blog-post-list/luxury.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-list/luxury')),
  },
  {
    name: 'blog-post-carousel-electric',
    dependencies: [],
    registryDependencies: ['blog-post-carousel-electric'],
    files: ['examples/sections/blog-post-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-carousel/electric')),
  },
  {
    name: 'blog-post-carousel-warm',
    dependencies: [],
    registryDependencies: ['blog-post-carousel-warm'],
    files: ['examples/sections/blog-post-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-carousel/warm')),
  },
  {
    name: 'blog-post-carousel-luxury',
    dependencies: [],
    registryDependencies: ['blog-post-carousel-luxury'],
    files: ['examples/sections/blog-post-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/blog-post-carousel/luxury')),
  },
  {
    name: 'breadcrumbs-electric',
    dependencies: [],
    registryDependencies: ['breadcrumbs-electric'],
    files: ['examples/sections/breadcrumbs/electric.tsx'],
    component: lazy(() => import('./examples/sections/breadcrumbs/electric')),
  },
  {
    name: 'breadcrumbs-warm',
    dependencies: [],
    registryDependencies: ['breadcrumbs-warm'],
    files: ['examples/sections/breadcrumbs/warm.tsx'],
    component: lazy(() => import('./examples/sections/breadcrumbs/warm')),
  },
  {
    name: 'breadcrumbs-luxury',
    dependencies: [],
    registryDependencies: ['breadcrumbs-luxury'],
    files: ['examples/sections/breadcrumbs/luxury.tsx'],
    component: lazy(() => import('./examples/sections/breadcrumbs/luxury')),
  },
  {
    name: 'button-example',
    dependencies: [],
    registryDependencies: ['button'],
    files: ['examples/primitives/button/index.tsx'],
    component: lazy(() => import('./examples/primitives/button')),
  },
  {
    name: 'button-link-example',
    dependencies: [],
    registryDependencies: ['button-link'],
    files: ['examples/primitives/button-link/index.tsx'],
    component: lazy(() => import('./examples/primitives/button-link')),
  },
  {
    name: 'button-radio-group-example',
    dependencies: [],
    registryDependencies: ['button-radio-group'],
    files: ['examples/form/button-radio-group/index.tsx'],
    component: lazy(() => import('./examples/form/button-radio-group')),
  },
  {
    name: 'calendar-electric',
    dependencies: [],
    registryDependencies: ['calendar'],
    files: ['examples/primitives/calendar/electric.tsx'],
    component: lazy(() => import('./examples/primitives/calendar/electric')),
  },
  {
    name: 'calendar-warm',
    dependencies: [],
    registryDependencies: ['calendar'],
    files: ['examples/primitives/calendar/warm.tsx'],
    component: lazy(() => import('./examples/primitives/calendar/warm')),
  },
  {
    name: 'calendar-luxury',
    dependencies: [],
    registryDependencies: ['calendar'],
    files: ['examples/primitives/calendar/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/calendar/luxury')),
  },
  {
    name: 'card-carousel-electric',
    dependencies: [],
    registryDependencies: ['card-carousel-electric'],
    files: ['examples/sections/card-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/card-carousel/electric')),
  },
  {
    name: 'card-carousel-warm',
    dependencies: [],
    registryDependencies: ['card-carousel-warm'],
    files: ['examples/sections/card-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/card-carousel/warm')),
  },
  {
    name: 'card-carousel-luxury',
    dependencies: [],
    registryDependencies: ['card-carousel-luxury'],
    files: ['examples/sections/card-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/card-carousel/luxury')),
  },
  {
    name: 'card-example',
    dependencies: [],
    registryDependencies: ['card'],
    files: ['examples/primitives/card/index.tsx'],
    component: lazy(() => import('./examples/primitives/card')),
  },
  {
    name: 'card-radio-group-example',
    dependencies: [],
    registryDependencies: ['card-radio-group'],
    files: ['examples/form/card-radio-group/index.tsx'],
    component: lazy(() => import('./examples/form/card-radio-group')),
  },
  {
    name: 'carousel-warm',
    dependencies: ['embla-carousel-react', 'lucide-react', 'clsx'],
    registryDependencies: [],
    files: ['examples/primitives/carousel/warm.tsx'],
    component: lazy(() => import('./examples/primitives/carousel/warm')),
  },
  {
    name: 'carousel-electric',
    dependencies: ['embla-carousel-react', 'lucide-react', 'clsx'],
    registryDependencies: [],
    files: ['examples/primitives/carousel/electric.tsx'],
    component: lazy(() => import('./examples/primitives/carousel/electric')),
  },
  {
    name: 'carousel-luxury',
    dependencies: ['embla-carousel-react', 'lucide-react', 'clsx'],
    registryDependencies: [],
    files: ['examples/primitives/carousel/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/carousel/luxury')),
  },
  {
    name: 'cart-electric',
    dependencies: [],
    registryDependencies: ['cart-electric'],
    files: ['examples/sections/cart/electric.tsx'],
    component: lazy(() => import('./examples/sections/cart/electric')),
  },
  {
    name: 'cart-warm',
    dependencies: [],
    registryDependencies: ['cart-warm'],
    files: ['examples/sections/cart/warm.tsx'],
    component: lazy(() => import('./examples/sections/cart/warm')),
  },
  {
    name: 'cart-luxury',
    dependencies: [],
    registryDependencies: ['cart-luxury'],
    files: ['examples/sections/cart/luxury.tsx'],
    component: lazy(() => import('./examples/sections/cart/luxury')),
  },
  {
    name: 'chip-example',
    dependencies: [],
    registryDependencies: ['chip'],
    files: ['examples/primitives/chip/index.tsx'],
    component: lazy(() => import('./examples/primitives/chip')),
  },
  {
    name: 'compare-section-electric-example',
    dependencies: [],
    registryDependencies: ['compare-section'],
    files: ['examples/sections/compare-section/electric.tsx'],
    component: lazy(() => import('./examples/sections/compare-section/electric')),
  },
  {
    name: 'compare-section-luxury-example',
    dependencies: [],
    registryDependencies: ['compare-section'],
    files: ['examples/sections/compare-section/luxury.tsx'],
    component: lazy(() => import('./examples/sections/compare-section/luxury')),
  },
  {
    name: 'compare-section-warm-example',
    dependencies: [],
    registryDependencies: ['compare-section'],
    files: ['examples/sections/compare-section/warm.tsx'],
    component: lazy(() => import('./examples/sections/compare-section/warm')),
  },
  {
    name: 'countdown-example',
    dependencies: [],
    registryDependencies: ['countdown'],
    files: ['examples/sections/countdown/index.tsx'],
    component: lazy(() => import('./examples/sections/countdown')),
  },
  {
    name: 'counter-example',
    dependencies: [],
    registryDependencies: ['counter'],
    files: ['examples/primitives/counter/index.tsx'],
    component: lazy(() => import('./examples/primitives/counter')),
  },
  {
    name: 'cursor-pagination-example',
    dependencies: [],
    registryDependencies: ['cursor-pagination'],
    files: ['examples/primitives/cursor-pagination/index.tsx'],
    component: lazy(() => import('./examples/primitives/cursor-pagination')),
  },
  {
    name: 'date-picker-example',
    dependencies: [],
    registryDependencies: ['date-picker'],
    files: ['examples/form/date-picker/index.tsx'],
    component: lazy(() => import('./examples/form/date-picker')),
  },
  {
    name: 'discount-example',
    dependencies: [],
    registryDependencies: ['discount'],
    files: ['examples/sections/discount/index.tsx'],
    component: lazy(() => import('./examples/sections/discount')),
  },
  {
    name: 'dynamic-form-example',
    dependencies: [],
    registryDependencies: ['dynamic-form'],
    files: ['examples/form/dynamic-form/index.tsx'],
    component: lazy(() => import('./examples/form/dynamic-form')),
  },
  {
    name: 'favorite-example',
    dependencies: [],
    registryDependencies: ['favorite'],
    files: ['examples/primitives/favorite/index.tsx'],
    component: lazy(() => import('./examples/primitives/favorite')),
  },
  {
    name: 'feature-electric-example',
    dependencies: [],
    registryDependencies: ['feature-electric'],
    files: ['examples/sections/feature/electric.tsx'],
    component: lazy(() => import('./examples/sections/feature/electric')),
  },
  {
    name: 'feature-warm-example',
    dependencies: [],
    registryDependencies: ['feature-warm'],
    files: ['examples/sections/feature/warm.tsx'],
    component: lazy(() => import('./examples/sections/feature/warm')),
  },
  {
    name: 'feature-luxury-example',
    dependencies: [],
    registryDependencies: ['feature-luxury'],
    files: ['examples/sections/feature/luxury.tsx'],
    component: lazy(() => import('./examples/sections/feature/luxury')),
  },
  {
    name: 'feature-grid-electric-example',
    dependencies: [],
    registryDependencies: ['feature-grid-electric'],
    files: ['examples/sections/feature-grid/electric.tsx'],
    component: lazy(() => import('./examples/sections/feature-grid/electric')),
  },
  {
    name: 'feature-grid-warm-example',
    dependencies: [],
    registryDependencies: ['feature-grid-warm'],
    files: ['examples/sections/feature-grid/warm.tsx'],
    component: lazy(() => import('./examples/sections/feature-grid/warm')),
  },
  {
    name: 'feature-grid-luxury-example',
    dependencies: [],
    registryDependencies: ['feature-grid-luxury'],
    files: ['examples/sections/feature-grid/luxury.tsx'],
    component: lazy(() => import('./examples/sections/feature-grid/luxury')),
  },
  {
    name: 'featured-blog-post-carousel-warm',
    dependencies: [],
    registryDependencies: ['blog-post-carousel', 'animated-link'],
    files: ['examples/sections/featured-blog-post-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-carousel/warm')),
  },
  {
    name: 'featured-blog-post-carousel-electric',
    dependencies: [],
    registryDependencies: ['blog-post-carousel', 'animated-link'],
    files: ['examples/sections/featured-blog-post-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-carousel/electric')),
  },
  {
    name: 'featured-blog-post-carousel-luxury',
    dependencies: [],
    registryDependencies: ['blog-post-carousel', 'animated-link'],
    files: ['examples/sections/featured-blog-post-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-carousel/luxury')),
  },
  {
    name: 'featured-blog-post-list-example-warm',
    dependencies: [],
    registryDependencies: ['featured-blog-post-list'],
    files: ['examples/sections/featured-blog-post-list/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-list/warm')),
  },
  {
    name: 'featured-blog-post-list-example-electric',
    dependencies: [],
    registryDependencies: ['featured-blog-post-list'],
    files: ['examples/sections/featured-blog-post-list/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-list/electric')),
  },
  {
    name: 'featured-blog-post-list-example-luxury',
    dependencies: [],
    registryDependencies: ['featured-blog-post-list'],
    files: ['examples/sections/featured-blog-post-list/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-blog-post-list/luxury')),
  },
  {
    name: 'featured-card-carousel-electric',
    dependencies: [],
    registryDependencies: ['featured-card-carousel'],
    files: ['examples/sections/featured-card-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-card-carousel/electric')),
  },
  {
    name: 'featured-card-carousel-luxury',
    dependencies: [],
    registryDependencies: ['featured-card-carousel'],
    files: ['examples/sections/featured-card-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-card-carousel/luxury')),
  },
  {
    name: 'featured-card-carousel-warm',
    dependencies: [],
    registryDependencies: ['featured-card-carousel'],
    files: ['examples/sections/featured-card-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-card-carousel/warm')),
  },
  {
    name: 'featured-image-electric-example',
    dependencies: [],
    registryDependencies: ['featured-image-electric'],
    files: ['examples/sections/featured-image/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-image/electric')),
  },
  {
    name: 'featured-image-warm-example',
    dependencies: [],
    registryDependencies: ['featured-image-warm'],
    files: ['examples/sections/featured-image/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-image/warm')),
  },
  {
    name: 'featured-image-luxury-example',
    dependencies: [],
    registryDependencies: ['featured-image-luxury'],
    files: ['examples/sections/featured-image/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-image/luxury')),
  },
  {
    name: 'featured-product-carousel-electric',
    dependencies: [],
    registryDependencies: ['featured-product-carousel'],
    files: ['examples/sections/featured-product-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-carousel/electric')),
  },
  {
    name: 'featured-product-carousel-warm',
    dependencies: [],
    registryDependencies: ['featured-product-carousel'],
    files: ['examples/sections/featured-product-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-carousel/warm')),
  },
  {
    name: 'featured-product-carousel-luxury',
    dependencies: [],
    registryDependencies: ['featured-product-carousel'],
    files: ['examples/sections/featured-product-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-carousel/luxury')),
  },
  {
    name: 'featured-product-list-electric',
    dependencies: [],
    registryDependencies: ['featured-product-list-electric'],
    files: ['examples/sections/featured-product-list/electric.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-list/electric')),
  },
  {
    name: 'featured-product-list-warm',
    dependencies: [],
    registryDependencies: ['featured-product-list-warm'],
    files: ['examples/sections/featured-product-list/warm.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-list/warm')),
  },
  {
    name: 'featured-product-list-luxury',
    dependencies: [],
    registryDependencies: ['featured-product-list-luxury'],
    files: ['examples/sections/featured-product-list/luxury.tsx'],
    component: lazy(() => import('./examples/sections/featured-product-list/luxury')),
  },
  {
    name: 'featured-video-example',
    dependencies: [],
    registryDependencies: ['featured-video'],
    files: ['examples/sections/featured-video/index.tsx'],
    component: lazy(() => import('./examples/sections/featured-video')),
  },
  {
    name: 'field-error-example',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['/examples/form/field-error/index.tsx'],
    component: lazy(() => import('./examples/form/field-error')),
  },
  {
    name: 'form-status-example',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/form/form-status/index.tsx'],
    component: lazy(() => import('./examples/form/form-status/index')),
  },
  {
    name: 'footer-electric-example',
    dependencies: [],
    registryDependencies: ['footer-electric'],
    files: ['examples/sections/footer/electric.tsx'],
    component: lazy(() => import('./examples/sections/footer/electric')),
  },
  {
    name: 'footer-warm-example',
    dependencies: [],
    registryDependencies: ['footer-warm'],
    files: ['examples/sections/footer/warm.tsx'],
    component: lazy(() => import('./examples/sections/footer/warm')),
  },
  {
    name: 'footer-luxury-example',
    dependencies: [],
    registryDependencies: ['footer-luxury'],
    files: ['examples/sections/footer/luxury.tsx'],
    component: lazy(() => import('./examples/sections/footer/luxury')),
  },
  {
    name: 'forgot-password-example',
    dependencies: [],
    registryDependencies: ['forgot-password'],
    files: ['examples/sections/forgot-password/index.tsx'],
    component: lazy(() => import('./examples/sections/forgot-password')),
  },
  {
    name: 'form-status-example',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/form/form-status/index.tsx'],
    component: lazy(() => import('./examples/form/form-status/index')),
  },
  {
    name: 'header-electric',
    dependencies: [],
    registryDependencies: ['header'],
    files: ['examples/sections/header/electric.tsx'],
    component: lazy(() => import('./examples/sections/header/electric')),
  },
  {
    name: 'header-warm',
    dependencies: [],
    registryDependencies: ['header'],
    files: ['examples/sections/header/warm.tsx'],
    component: lazy(() => import('./examples/sections/header/warm')),
  },
  {
    name: 'header-luxury',
    dependencies: [],
    registryDependencies: ['header'],
    files: ['examples/sections/header/luxury.tsx'],
    component: lazy(() => import('./examples/sections/header/luxury')),
  },
  {
    name: 'icon-example',
    dependencies: [],
    registryDependencies: ['icon'],
    files: ['examples/primitives/icon/index.tsx'],
    component: lazy(() => import('./examples/primitives/icon')),
  },
  {
    name: 'icon-block-example',
    dependencies: [],
    registryDependencies: ['icon-block'],
    files: ['examples/sections/icon-block/index.tsx'],
    component: lazy(() => import('./examples/sections/icon-block')),
  },
  {
    name: 'inline-email-form-example',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/inline-email-form/index.tsx'],
    component: lazy(() => import('./examples/sections/inline-email-form')),
  },
  {
    name: 'input-example',
    dependencies: [],
    registryDependencies: ['input'],
    files: ['examples/form/input/index.tsx'],
    component: lazy(() => import('./examples/form/input')),
  },
  {
    name: 'logo-example',
    dependencies: [],
    registryDependencies: ['logo'],
    files: ['examples/primitives/logo/index.tsx'],
    component: lazy(() => import('./examples/primitives/logo')),
  },
  {
    name: 'modal-example',
    dependencies: [],
    registryDependencies: ['modal'],
    files: ['examples/primitives/modal/index.tsx'],
    component: lazy(() => import('./examples/primitives/modal')),
  },
  {
    name: 'logo-example',
    dependencies: ['clsx'],
    registryDependencies: ['streamable'],
    files: ['examples/primitives/logo/index.tsx'],
    component: lazy(() => import('./examples/primitives/logo')),
  },
  {
    name: 'navigation-electric',
    dependencies: [],
    registryDependencies: ['navigation-electric'],
    files: ['examples/primitives/navigation/electric.tsx'],
    component: lazy(() => import('./examples/primitives/navigation/electric')),
  },
  {
    name: 'navigation-warm',
    dependencies: [],
    registryDependencies: ['navigation-warm'],
    files: ['examples/primitives/navigation/warm.tsx'],
    component: lazy(() => import('./examples/primitives/navigation/warm')),
  },
  {
    name: 'navigation-luxury',
    dependencies: [],
    registryDependencies: ['navigation-luxury'],
    files: ['examples/primitives/navigation/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/navigation/luxury')),
  },
  {
    name: 'not-found-example',
    dependencies: [],
    registryDependencies: ['section-layout'],
    files: ['examples/sections/not-found/index.tsx'],
    component: lazy(() => import('./examples/sections/not-found')),
  },
  {
    name: 'number-input-example',
    dependencies: [],
    registryDependencies: ['number-input'],
    files: ['examples/form/number-input/index.tsx'],
    component: lazy(() => import('./examples/form/number-input')),
  },
  {
    name: 'order-details-section-electric',
    dependencies: [],
    registryDependencies: ['order-details-section'],
    files: ['examples/sections/order-details-section/electric.tsx'],
    component: lazy(() => import('./examples/sections/order-details-section/electric')),
  },
  {
    name: 'order-details-section-luxury',
    dependencies: [],
    registryDependencies: ['order-details-section'],
    files: ['examples/sections/order-details-section/luxury.tsx'],
    component: lazy(() => import('./examples/sections/order-details-section/luxury')),
  },
  {
    name: 'order-details-section-warm',
    dependencies: [],
    registryDependencies: ['order-details-section'],
    files: ['examples/sections/order-details-section/warm.tsx'],
    component: lazy(() => import('./examples/sections/order-details-section/warm')),
  },
  {
    name: 'order-list-electric',
    dependencies: [],
    registryDependencies: ['order-list'],
    files: ['examples/sections/order-list/electric.tsx'],
    component: lazy(() => import('./examples/sections/order-list/electric')),
  },
  {
    name: 'order-list-luxury',
    dependencies: [],
    registryDependencies: ['order-list'],
    files: ['examples/sections/order-list/luxury.tsx'],
    component: lazy(() => import('./examples/sections/order-list/luxury')),
  },
  {
    name: 'order-list-warm',
    dependencies: [],
    registryDependencies: ['order-list'],
    files: ['examples/sections/order-list/warm.tsx'],
    component: lazy(() => import('./examples/sections/order-list/warm')),
  },
  {
    name: 'page-blog-example',
    dependencies: [],
    registryDependencies: ['page-blog'],
    files: ['examples/pages/blog/index.tsx'],
    component: lazy(() => import('./examples/pages/blog')),
  },
  {
    name: 'page-blog-post-electric-example',
    dependencies: [],
    registryDependencies: ['page-blog-post-electric'],
    files: ['examples/pages/blog/post/electric.tsx'],
    component: lazy(() => import('./examples/pages/blog/post/electric')),
  },
  {
    name: 'page-blog-post-warm-example',
    dependencies: [],
    registryDependencies: ['page-blog-post-warm'],
    files: ['examples/pages/blog/post/warm.tsx'],
    component: lazy(() => import('./examples/pages/blog/post/warm')),
  },
  {
    name: 'page-blog-post-luxury-example',
    dependencies: [],
    registryDependencies: ['page-blog-post-luxury'],
    files: ['examples/pages/blog/post/luxury.tsx'],
    component: lazy(() => import('./examples/pages/blog/post/luxury')),
  },
  {
    name: 'page-cart-electric-example',
    dependencies: [],
    registryDependencies: ['page-cart-electric'],
    files: ['examples/pages/cart/electric.tsx'],
    component: lazy(() => import('./examples/pages/cart/electric')),
  },
  {
    name: 'page-cart-warm-example',
    dependencies: [],
    registryDependencies: ['page-cart-warm'],
    files: ['examples/pages/cart/warm.tsx'],
    component: lazy(() => import('./examples/pages/cart/warm')),
  },
  {
    name: 'page-cart-luxury-example',
    dependencies: [],
    registryDependencies: ['page-cart-luxury'],
    files: ['examples/pages/cart/luxury.tsx'],
    component: lazy(() => import('./examples/pages/cart/luxury')),
  },
  {
    name: 'page-home-electric-example',
    dependencies: [],
    registryDependencies: ['page-home-electric'],
    files: ['examples/pages/home/electric.tsx'],
    component: lazy(() => import('./examples/pages/home/electric')),
  },
  {
    name: 'page-home-warm-example',
    dependencies: [],
    registryDependencies: ['page-home-warm'],
    files: ['examples/pages/home/warm.tsx'],
    component: lazy(() => import('./examples/pages/home/warm')),
  },
  {
    name: 'page-home-luxury-example',
    dependencies: [],
    registryDependencies: ['page-home-luxury'],
    files: ['examples/pages/home/luxury.tsx'],
    component: lazy(() => import('./examples/pages/home/luxury')),
  },
  {
    name: 'page-not-found-electric-example',
    dependencies: [],
    registryDependencies: ['page-not-found-electric'],
    files: ['examples/pages/not-found/electric.tsx'],
    component: lazy(() => import('./examples/pages/not-found/electric')),
  },
  {
    name: 'page-not-found-warm-example',
    dependencies: [],
    registryDependencies: ['page-not-found-warm'],
    files: ['examples/pages/not-found/warm.tsx'],
    component: lazy(() => import('./examples/pages/not-found/warm')),
  },
  {
    name: 'page-not-found-luxury-example',
    dependencies: [],
    registryDependencies: ['page-not-found-luxury'],
    files: ['examples/pages/not-found/luxury.tsx'],
    component: lazy(() => import('./examples/pages/not-found/luxury')),
  },
  {
    name: 'page-error-example',
    dependencies: [],
    registryDependencies: ['page-error'],
    files: ['examples/pages/error/index.tsx'],
    component: lazy(() => import('./examples/pages/error')),
  },
  {
    name: 'page-maintenance-example',
    dependencies: [],
    registryDependencies: ['page-maintenance'],
    files: ['examples/pages/maintenance/index.tsx'],
    component: lazy(() => import('./examples/pages/maintenance')),
  },
  {
    name: 'page-product-electric-example',
    dependencies: [],
    registryDependencies: ['page-product-electric'],
    files: ['examples/pages/product/electric.tsx'],
    component: lazy(() => import('./examples/pages/product/electric')),
  },
  {
    name: 'page-product-warm-example',
    dependencies: [],
    registryDependencies: ['page-product-warm'],
    files: ['examples/pages/product/warm.tsx'],
    component: lazy(() => import('./examples/pages/product/warm')),
  },
  {
    name: 'page-product-luxury-example',
    dependencies: [],
    registryDependencies: ['page-product-luxury'],
    files: ['examples/pages/product/luxury.tsx'],
    component: lazy(() => import('./examples/pages/product/luxury')),
  },
  {
    name: 'page-products-electric-example',
    dependencies: [],
    registryDependencies: ['page-products-electric'],
    files: ['examples/pages/products/electric.tsx'],
    component: lazy(() => import('./examples/pages/products/electric')),
  },
  {
    name: 'page-products-warm-example',
    dependencies: [],
    registryDependencies: ['page-products-warm'],
    files: ['examples/pages/products/warm.tsx'],
    component: lazy(() => import('./examples/pages/products/warm')),
  },
  {
    name: 'page-products-luxury-example',
    dependencies: [],
    registryDependencies: ['page-products-luxury'],
    files: ['examples/pages/products/luxury.tsx'],
    component: lazy(() => import('./examples/pages/products/luxury')),
  },
  {
    name: 'offset-pagination-example',
    dependencies: [],
    registryDependencies: ['offset-pagination'],
    files: ['examples/primitives/offset-pagination/index.tsx'],
    component: lazy(() => import('./examples/primitives/offset-pagination')),
  },
  {
    name: 'price-label-example',
    dependencies: [],
    registryDependencies: ['price-label'],
    files: ['examples/primitives/price-label/index.tsx'],
    component: lazy(() => import('./examples/primitives/price-label')),
  },
  {
    name: 'product-card-warm',
    dependencies: [],
    registryDependencies: ['product-card'],
    files: ['examples/primitives/product-card/warm.tsx'],
    component: lazy(() => import('./examples/primitives/product-card/warm')),
  },
  {
    name: 'product-card-electric',
    dependencies: [],
    registryDependencies: ['product-card'],
    files: ['examples/primitives/product-card/electric.tsx'],
    component: lazy(() => import('./examples/primitives/product-card/electric')),
  },
  {
    name: 'product-card-luxury',
    dependencies: [],
    registryDependencies: ['product-card'],
    files: ['examples/primitives/product-card/luxury.tsx'],
    component: lazy(() => import('./examples/primitives/product-card/luxury')),
  },
  {
    name: 'product-carousel-warm',
    dependencies: [],
    registryDependencies: ['product-carousel'],
    files: ['examples/sections/product-carousel/warm.tsx'],
    component: lazy(() => import('./examples/sections/product-carousel/warm')),
  },
  {
    name: 'product-carousel-electric',
    dependencies: [],
    registryDependencies: ['product-carousel'],
    files: ['examples/sections/product-carousel/electric.tsx'],
    component: lazy(() => import('./examples/sections/product-carousel/electric')),
  },
  {
    name: 'product-carousel-luxury',
    dependencies: [],
    registryDependencies: ['product-carousel'],
    files: ['examples/sections/product-carousel/luxury.tsx'],
    component: lazy(() => import('./examples/sections/product-carousel/luxury')),
  },
  {
    name: 'product-detail-electric-example',
    dependencies: [],
    registryDependencies: ['product-detail'],
    files: ['examples/sections/product-detail/electric.tsx'],
    component: lazy(() => import('./examples/sections/product-detail/electric')),
  },
  {
    name: 'product-detail-warm-example',
    dependencies: [],
    registryDependencies: ['product-detail'],
    files: ['examples/sections/product-detail/warm.tsx'],
    component: lazy(() => import('./examples/sections/product-detail/warm')),
  },
  {
    name: 'product-detail-luxury-example',
    dependencies: [],
    registryDependencies: ['product-detail'],
    files: ['examples/sections/product-detail/luxury.tsx'],
    component: lazy(() => import('./examples/sections/product-detail/luxury')),
  },
  {
    name: 'product-list-electric',
    dependencies: [],
    registryDependencies: ['product-list-electric'],
    files: ['examples/sections/product-list/electric.tsx'],
    component: lazy(() => import('./examples/sections/product-list/electric')),
  },
  {
    name: 'product-list-warm',
    dependencies: [],
    registryDependencies: ['product-list-warm'],
    files: ['examples/sections/product-list/warm.tsx'],
    component: lazy(() => import('./examples/sections/product-list/warm')),
  },
  {
    name: 'product-list-luxury',
    dependencies: [],
    registryDependencies: ['product-list-luxury'],
    files: ['examples/sections/product-list/luxury.tsx'],
    component: lazy(() => import('./examples/sections/product-list/luxury')),
  },
  {
    name: 'product-list-section-electric',
    dependencies: [],
    registryDependencies: ['product-list-section'],
    files: ['examples/sections/product-list-section/electric.tsx'],
    component: lazy(() => import('./examples/sections/product-list-section/electric')),
  },
  {
    name: 'product-list-section-warm',
    dependencies: [],
    registryDependencies: ['product-list-section'],
    files: ['examples/sections/product-list-section/warm.tsx'],
    component: lazy(() => import('./examples/sections/product-list-section/warm')),
  },
  {
    name: 'product-list-section-luxury',
    dependencies: [],
    registryDependencies: ['product-list-section'],
    files: ['examples/sections/product-list-section/luxury.tsx'],
    component: lazy(() => import('./examples/sections/product-list-section/luxury')),
  },
  {
    name: 'radio-group-example',
    dependencies: [],
    registryDependencies: ['radio-group'],
    files: ['examples/form/radio-group/index.tsx'],
    component: lazy(() => import('./examples/form/radio-group')),
  },
  {
    name: 'rating-example',
    dependencies: [],
    registryDependencies: ['rating'],
    files: ['examples/primitives/rating/index.tsx'],
    component: lazy(() => import('./examples/primitives/rating')),
  },
  {
    name: 'reset-password-example',
    dependencies: [],
    registryDependencies: ['reset-password'],
    files: ['examples/sections/reset-password/index.tsx'],
    component: lazy(() => import('./examples/sections/reset-password')),
  },
  {
    name: 'reviews-example',
    dependencies: [],
    registryDependencies: ['reviews'],
    files: ['examples/sections/reviews/index.tsx'],
    component: lazy(() => import('./examples/sections/reviews')),
  },
  {
    name: 'select-example',
    dependencies: [],
    registryDependencies: ['select'],
    files: ['examples/form/select/index.tsx'],
    component: lazy(() => import('./examples/form/select')),
  },
  {
    name: 'side-panel-example',
    dependencies: [],
    registryDependencies: ['side-panel'],
    files: ['examples/primitives/side-panel/index.tsx'],
    component: lazy(() => import('./examples/primitives/side-panel')),
  },
  {
    name: 'sign-in-example',
    dependencies: [],
    registryDependencies: ['sign-in'],
    files: ['examples/sections/sign-in/index.tsx'],
    component: lazy(() => import('./examples/sections/sign-in')),
  },
  {
    name: 'skeleton-example',
    dependencies: [],
    registryDependencies: ['sign-in'],
    files: ['examples/primitives/skeleton/index.tsx'],
    component: lazy(() => import('./examples/primitives/skeleton')),
  },
  {
    name: 'dynamic-form-section-example',
    dependencies: [],
    registryDependencies: ['dynamic-form-section'],
    files: ['examples/sections/dynamic-form-section/index.tsx'],
    component: lazy(() => import('./examples/sections/dynamic-form-section')),
  },
  {
    name: 'slideshow-example-electric',
    dependencies: [],
    registryDependencies: ['slideshow-electric'],
    files: ['examples/sections/slideshow/electric.tsx'],
    component: lazy(() => import('./examples/sections/slideshow/electric')),
  },
  {
    name: 'slideshow-example-warm',
    dependencies: [],
    registryDependencies: ['slideshow-warm'],
    files: ['examples/sections/slideshow/warm.tsx'],
    component: lazy(() => import('./examples/sections/slideshow/warm')),
  },
  {
    name: 'slideshow-example-luxury',
    dependencies: [],
    registryDependencies: ['slideshow-luxury'],
    files: ['examples/sections/slideshow/luxury.tsx'],
    component: lazy(() => import('./examples/sections/slideshow/luxury')),
  },
  {
    name: 'spinner-example',
    dependencies: [],
    registryDependencies: ['spinner'],
    files: ['examples/primitives/spinner/index.tsx'],
    component: lazy(() => import('./examples/primitives/spinner')),
  },
  {
    name: 'subscribe-example',
    dependencies: [],
    registryDependencies: ['subscribe'],
    files: ['examples/sections/subscribe/index.tsx'],
    component: lazy(() => import('./examples/sections/subscribe')),
  },
  {
    name: 'swatch-radio-group-example',
    dependencies: [],
    registryDependencies: ['swatch-radio-group'],
    files: ['examples/form/swatch-radio-group/index.tsx'],
    component: lazy(() => import('./examples/form/swatch-radio-group')),
  },
  {
    name: 'switch-example',
    dependencies: [],
    registryDependencies: ['switch'],
    files: ['examples/form/switch/index.tsx'],
    component: lazy(() => import('./examples/form/switch')),
  },
  {
    name: 'textarea-example',
    dependencies: [],
    registryDependencies: ['textarea'],
    files: ['examples/form/textarea/index.tsx'],
    component: lazy(() => import('./examples/form/textarea')),
  },
  {
    name: 'toaster-example',
    dependencies: [],
    registryDependencies: ['toaster'],
    files: ['examples/primitives/toaster/index.tsx'],
    component: lazy(() => import('./examples/primitives/toaster')),
  },
  {
    name: 'section-layout-example-warm',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/section-layout/warm.tsx'],
    component: lazy(() => import('./examples/sections/section-layout/warm')),
  },
  {
    name: 'section-layout-example-electric',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/section-layout/electric.tsx'],
    component: lazy(() => import('./examples/sections/section-layout/electric')),
  },
  {
    name: 'section-layout-example-luxury',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/section-layout/luxury.tsx'],
    component: lazy(() => import('./examples/sections/section-layout/luxury')),
  },
  {
    name: 'error-example-warm',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/error/warm.tsx'],
    component: lazy(() => import('./examples/sections/error/warm')),
  },
  {
    name: 'error-example-electric',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/error/electric.tsx'],
    component: lazy(() => import('./examples/sections/error/electric')),
  },
  {
    name: 'error-example-luxury',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/error/luxury.tsx'],
    component: lazy(() => import('./examples/sections/error/luxury')),
  },
  {
    name: 'maintenance-electric',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/maintenance/electric.tsx'],
    component: lazy(() => import('./examples/sections/maintenance/electric')),
  },
  {
    name: 'maintenance-warm',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/maintenance/warm.tsx'],
    component: lazy(() => import('./examples/sections/maintenance/warm')),
  },
  {
    name: 'maintenance-luxury',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/maintenance/luxury.tsx'],
    component: lazy(() => import('./examples/sections/maintenance/luxury')),
  },
  {
    name: 'sticky-sidebar-layout-example-warm',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/sticky-sidebar-layout/warm.tsx'],
    component: lazy(() => import('./examples/sections/sticky-sidebar-layout/warm')),
  },
  {
    name: 'sticky-sidebar-layout-example-electric',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/sticky-sidebar-layout/electric.tsx'],
    component: lazy(() => import('./examples/sections/sticky-sidebar-layout/electric')),
  },
  {
    name: 'sticky-sidebar-layout-example-luxury',
    dependencies: [],
    registryDependencies: [],
    files: ['examples/sections/sticky-sidebar-layout/luxury.tsx'],
    component: lazy(() => import('./examples/sections/sticky-sidebar-layout/luxury')),
  },
  // PLOP: Append new component here
] satisfies Components;
