import { Navigation } from '@/vibes/schema';

export const navigation = [
  {
    title: 'Getting started',
    pages: [
      { title: 'Introduction', slug: 'introduction', file: 'docs/introduction.mdx' },
      { title: 'Installation', slug: 'installation', file: 'docs/installation.mdx' },
    ],
  },
  {
    title: 'Styles',
    pages: [
      { title: 'Electric', slug: 'electric', file: 'docs/electric.mdx' },
      { title: 'Warm', slug: 'warm', file: 'docs/warm.mdx' },
      { title: 'Luxury', slug: 'luxury', file: 'docs/luxury.mdx' },
    ],
  },
  {
    title: 'Primitives',
    pages: [
      {
        title: 'Accordion',
        slug: 'accordion',
        file: 'docs/accordion.mdx',
        component: 'accordion',
      },
      {
        title: 'Alert',
        slug: 'alert',
        file: 'docs/alert.mdx',
        component: 'alert',
      },
      {
        title: 'Animated Link',
        slug: 'animated-link',
        file: 'docs/animated-link.mdx',
        component: 'animated-link',
      },
      { title: 'Badge', slug: 'badge', file: 'docs/badge.mdx', component: 'badge' },
      {
        title: 'Banner',
        slug: 'banner',
        file: 'docs/banner.mdx',
        component: 'banner',
      },
      {
        title: 'Blog Post Card',
        slug: 'blog-post-card',
        file: 'docs/blog-post-card.mdx',
        component: 'blog-post-card',
      },
      {
        title: 'Blog Post List',
        slug: 'blog-post-list',
        file: 'docs/blog-post-list.mdx',
        component: 'blog-post-list',
      },
      { title: 'Button', slug: 'button', file: 'docs/button.mdx', component: 'button' },
      {
        title: 'Button Link',
        slug: 'button-link',
        file: 'docs/button-link.mdx',
        component: 'button-link',
      },
      {
        title: 'Calendar',
        slug: 'calendar',
        file: 'docs/calendar.mdx',
        component: 'calendar',
      },
      {
        title: 'Card',
        slug: 'card',
        file: 'docs/card.mdx',
        component: 'card',
      },
      {
        title: 'Carousel',
        slug: 'carousel',
        file: 'docs/carousel.mdx',
        component: 'carousel',
      },
      { title: 'Chip', slug: 'chip', file: 'docs/chip.mdx', component: 'chip' },
      {
        title: 'Compare Card',
        slug: 'compare-card',
        file: 'docs/compare-card.mdx',
        component: 'compare-card',
      },
      {
        title: 'Compare Drawer',
        slug: 'compare-drawer',
        file: 'docs/compare-drawer.mdx',
        component: 'compare-drawer',
      },
      { title: 'Counter', slug: 'counter', file: 'docs/counter.mdx', component: 'counter' },
      {
        title: 'Cursor Pagination',
        slug: 'cursor-pagination',
        file: 'docs/cursor-pagination.mdx',
        component: 'cursor-pagination',
      },
      { title: 'Discount', slug: 'discount', file: 'docs/discount.mdx', component: 'discount' },
      { title: 'Favorite', slug: 'favorite', file: 'docs/favorite.mdx', component: 'favorite' },
      {
        title: 'Inline Email Form',
        slug: 'inline-email-form',
        file: 'docs/inline-email-form.mdx',
        component: 'inline-email-form',
      },
      {
        title: 'Navigation',
        slug: 'navigation',
        file: 'docs/navigation.mdx',
        component: 'navigation',
      },
      {
        title: 'Price Label',
        slug: 'price-label',
        file: 'docs/price-label.mdx',
        component: 'price-label',
      },
      {
        title: 'Offset Pagination',
        slug: 'offset-pagination',
        file: 'docs/offset-pagination.mdx',
        component: 'offset-pagination',
      },
      {
        title: 'Product Card',
        slug: 'product-card',
        file: 'docs/product-card.mdx',
        component: 'product-card',
      },
      {
        title: 'Product Carousel',
        slug: 'product-carousel',
        file: 'docs/products-carousel.mdx',
        component: 'products-carousel',
      },
      {
        title: 'Product List',
        slug: 'products-list',
        file: 'docs/products-list.mdx',
        component: 'products-list',
      },
      { title: 'Rating', slug: 'rating', file: 'docs/rating.mdx', component: 'rating' },
      {
        title: 'Skeleton',
        slug: 'skeleton',
        file: 'docs/skeleton.mdx',
        component: 'skeleton',
      },
      {
        title: 'Spinner',
        slug: 'spinner',
        file: 'docs/spinner.mdx',
        component: 'spinner',
      },
      {
        title: 'Streamable',
        slug: 'streamable',
        file: 'docs/streamable.mdx',
        component: 'streamable',
      },
      {
        title: 'Toaster',
        slug: 'toaster',
        file: 'docs/toaster.mdx',
        component: 'toaster',
      },
    ],
  },
  {
    title: 'Form',
    pages: [
      { title: 'Example', slug: 'form', file: 'docs/form.mdx' },
      { title: 'Checkbox', slug: 'checkbox', file: 'docs/checkbox.mdx', component: 'checkbox' },
      {
        title: 'Field Error',
        slug: 'field-error',
        file: 'docs/field-error.mdx',
        component: 'field-error',
      },
    ],
  },
  {
    title: 'Sections',
    pages: [
      {
        title: 'Account Settings Section',
        slug: 'account-settings-section',
        file: 'docs/account-settings-section.mdx',
        component: 'account-settings-section',
      },
      {
        title: 'Address List Section',
        slug: 'address-list-section',
        file: 'docs/address-list-section.mdx',
        component: 'address-list',
      },
      {
        title: 'Blog Post Carousel',
        slug: 'blog-post-carousel',
        file: 'docs/blog-post-carousel.mdx',
        component: 'blog-post-carousel',
      },
      {
        title: 'Breadcrumbs',
        slug: 'breadcrumbs',
        file: 'docs/breadcrumbs.mdx',
        component: 'breadcrumbs',
      },

      { title: 'Cart', slug: 'cart', file: 'docs/cart.mdx', component: 'cart' },
      {
        title: 'Card Carousel',
        slug: 'card-carousel',
        file: 'docs/card-carousel.mdx',
        component: 'card-carousel',
      },
      {
        title: 'Compare Section',
        slug: 'compare-section',
        file: 'docs/compare-section.mdx',
        component: 'compare-section',
      },
      { title: 'Countdown', slug: 'countdown', file: 'docs/countdown.mdx', component: 'countdown' },
      { title: 'Discount', slug: 'discount', file: 'docs/discount.mdx', component: 'discount' },
      {
        title: 'Dynamic Form Section',
        slug: 'dynamic-form-section',
        file: 'docs/dynamic-form-section.mdx',
        component: 'dynamic-form-section',
      },
      { title: 'Feature', slug: 'feature', file: 'docs/feature.mdx', component: 'feature-grid' },
      {
        title: 'Featured Blog Post Carousel',
        slug: 'featured-blog-post-carousel',
        file: 'docs/featured-blog-post-carousel.mdx',
        component: 'featured-blog-post-carousel',
      },
      {
        title: 'Featured Blog Post List',
        slug: 'featured-blog-post-list',
        file: 'docs/featured-blog-post-list.mdx',
        component: 'featured-blog-post-list',
      },
      {
        title: 'Featured Image',
        slug: 'featured-image',
        file: 'docs/featured-image.mdx',
        component: 'featured-image',
      },
      {
        title: 'Featured Products Carousel',
        slug: 'featured-products-carousel',
        file: 'docs/featured-products-carousel.mdx',
        component: 'featured-products-carousel',
      },
      {
        title: 'Featured Product List',
        slug: 'featured-products-list',
        file: 'docs/featured-products-list.mdx',
        component: 'featured-products-list',
      },
      {
        title: 'Featured Video',
        slug: 'featured-video',
        file: 'docs/featured-video.mdx',
        component: 'featured-video',
      },
      { title: 'Footer', slug: 'footer', file: 'docs/footer.mdx', component: 'footer' },
      {
        title: 'Forgot Password Section',
        slug: 'forgot-password-section',
        file: 'docs/forgot-password-section.mdx',
        component: 'forgot-password-section',
      },
      {
        title: 'Header',
        slug: 'header-section',
        file: 'docs/header-section.mdx',
        component: 'header-section',
      },
      {
        title: 'Icon Block',
        slug: 'icon-block',
        file: 'docs/icon-block.mdx',
        component: 'icon-block',
      },
      {
        title: 'Order Details Section',
        slug: 'order-details-section',
        file: 'docs/order-details-section.mdx',
        component: 'order-details-section',
      },
      {
        title: 'Order List Section',
        slug: 'order-list-section',
        file: 'docs/order-list-section.mdx',
        component: 'order-list-section',
      },
      {
        title: 'Product Carousel',
        slug: 'product-carousel',
        file: 'docs/product-carousel.mdx',
        component: 'product-carousel',
      },
      {
        title: 'Product List',
        slug: 'product-list',
        file: 'docs/product-list.mdx',
        component: 'product-list',
      },
      {
        title: 'Product List Section',
        slug: 'product-list-section',
        file: 'docs/products-list-section.mdx',
        component: 'products-list-section',
      },
      {
        title: 'Product Detail',
        slug: 'product-detail',
        file: 'docs/product-detail.mdx',
        component: 'product-detail',
      },
      {
        title: 'Reset Password Section',
        slug: 'reset-password-section',
        file: 'docs/reset-password-section.mdx',
        component: 'reset-password-section',
      },
      { title: 'Reviews', slug: 'reviews', file: 'docs/reviews.mdx', component: 'reviews' },
      {
        title: 'Sign In Section',
        slug: 'sign-in-section',
        file: 'docs/sign-in-section.mdx',
        component: 'sign-in-section',
      },
      {
        title: 'Slideshow',
        slug: 'slideshow',
        file: 'docs/slideshow.mdx',
        component: 'slideshow',
      },
      {
        title: 'Sticky Sidebar Layout',
        slug: 'sticky-sidebar-layout',
        file: 'docs/sticky-sidebar-layout.mdx',
        component: 'sticky-sidebar-layout',
      },
      {
        title: 'Subscribe',
        slug: 'subscribe',
        file: 'docs/subscribe.mdx',
        component: 'subscribe',
      },
    ],
  },
  {
    title: 'Pages',
    pages: [
      {
        title: 'Home',
        slug: 'page-home',
        file: 'docs/page-home.mdx',
      },
      {
        title: 'Products',
        slug: 'page-products',
        file: 'docs/page-products.mdx',
      },
      {
        title: 'Product',
        slug: 'page-product',
        file: 'docs/page-product.mdx',
      },
      {
        title: 'Cart',
        slug: 'page-cart',
        file: 'docs/page-cart.mdx',
      },
      {
        title: 'Blog',
        slug: 'page-blog',
        file: 'docs/page-blog.mdx',
      },
      {
        title: 'Blog Post',
        slug: 'page-blog-post',
        file: 'docs/page-blog-post.mdx',
      },
      {
        title: 'Not Found',
        slug: 'page-not-found',
        file: 'docs/page-not-found.mdx',
      },
      {
        title: 'Error',
        slug: 'page-error',
        file: 'docs/page-error.mdx',
      },
      {
        title: 'Maintenance',
        slug: 'page-maintenance',
        file: 'docs/page-maintenance.mdx',
      },
    ],
  },
] satisfies Navigation;
