import { Components } from '@/vibes/schema';

export const primitives = [
  {
    name: 'accordions',
    dependencies: ['clsx', '@radix-ui/react-accordion'],
    registryDependencies: [],
    files: ['primitives/accordions/index.tsx'],
  },
  {
    name: 'alert',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/alert/index.tsx'],
  },
  {
    name: 'animated-link',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/animated-link/index.tsx'],
  },

  {
    name: 'badge',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/badge/index.tsx'],
  },
  {
    name: 'banner',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/banner/index.tsx'],
  },
  {
    name: 'blog-post-card',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/blog-post-card/index.tsx'],
  },
  {
    name: 'breadcrumbs',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/breadcrumbs/index.tsx'],
  },
  {
    name: 'button',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/button/index.tsx'],
  },
  {
    name: 'button-link',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/button-link/index.tsx'],
  },
  {
    name: 'calendar',
    dependencies: ['clsx', 'lucide-react', 'react-day-picker'],
    registryDependencies: [],
    files: ['primitives/calendar.tsx'],
  },
  {
    name: 'card',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/card/index.tsx'],
  },
  {
    name: 'card-carousel',
    dependencies: ['clsx'],
    registryDependencies: ['carousel'],
    files: ['primitives/card-carousel/index.tsx'],
  },
  {
    name: 'carousel',
    dependencies: ['embla-carousel-react', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/carousel/index.tsx'],
  },
  {
    name: 'checkbox',
    dependencies: ['clsx', 'lucide-react', '@radix-ui/react-checkbox'],
    registryDependencies: [],
    files: ['primitives/checkbox/index.tsx'],
  },
  {
    name: 'counter',
    dependencies: ['lucide-react'],
    registryDependencies: [],
    files: ['primitives/counter/index.tsx'],
  },
  {
    name: 'compare-card',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/compare-card/index.tsx'],
  },
  {
    name: 'counter',
    dependencies: ['clsx','lucide-react'],
    registryDependencies: [],
    files: ['primitives/counter/index.tsx'],
  },
  {
    name: 'cursor-pagination',
    dependencies: ['lucide-react', 'nuqs', 'clsx'],
    registryDependencies: [],
    files: ['primitives/cursor-pagination/index.tsx'],
  },
  {
    name: 'drawer',
    dependencies: ['@radix-ui/react-portal'],
    registryDependencies: [],
    files: ['primitives/drawer/index.tsx'],
  },
  {
    name: 'dropdown',
    dependencies: ['clsx', 'lucide-react', '@radix-ui/react-dropdown-menu'],
    registryDependencies: [],
    files: ['primitives/dropdown/index.tsx'],
  },
  {
    name: 'dynamic-form',
    dependencies: ['zod','@conform-to/react', '@conform-to/zod'],
    registryDependencies: [],
    files: ['primitives/dynamic-form/index.tsx','primitives/dynamic-form/schema.ts'],
  },
  {
    name: 'favorite',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: [
      'primitives/favorite/index.tsx',
      'primitives/favorite/heart.tsx',
      'primitives/favorite/styles.css',
    ],
  },
  {
    name: 'icon',
    dependencies: ['clsx','lucide-react'],
    registryDependencies: [],
    files: [
      'primitives/icon/index.tsx',
    ],
  },
  {
    name: 'inline-email-form',
    dependencies: ['lucide-react', '@conform-to/react', '@conform-to/zod'],
    registryDependencies: [],
    files: ['primitives/inline-email-form/index.tsx','primitives/inline-email-form/schema.ts'],
  },
  {
    name: 'input',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/input/index.tsx'],
  },
  {
    name: 'label',
    dependencies: ['clsx', '@radix-ui/react-label'],
    registryDependencies: [],
    files: ['primitives/label/index.tsx'],
  },
  {
    name: 'logo',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/logo/index.tsx'],
  },
  {
    name: 'modal',
    dependencies: ['clsx','@radix-ui/react-dialog'],
    registryDependencies: [],
    files: ['primitives/modal/index.tsx'],
  },
  {
    name: 'navigation',
    dependencies: ['clsx','@conform-to/react', '@radix-ui/react-dropdown-menu', '@radix-ui/react-navigation-menu', '@radix-ui/react-popover', 'lodash.debounce','lucid-react'],
    registryDependencies: [],
    files: ['primitives/navigation/index.tsx','primitives/navigation/schema.ts'],
  },
  {
    name: 'offset-pagination',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/offset-pagination/index.tsx'],
  },
  {
    name: 'price-label',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/price-label/index.tsx'],
  },
  {
    name: 'product-card',
    dependencies: ['clsx'],
    registryDependencies: ['badge', 'checkbox', 'price-label'],
    files: ['primitives/product-card/index.tsx', 'primitives/product-card/compare.tsx'],
  },
  {
    name: 'products-carousel',
    dependencies: ['clsx'],
    registryDependencies: ['product-card', 'carousel'],
    files: ['primitives/products-carousel/index.tsx'],
  },
  {
    name: 'products-list',
    dependencies: [],
    registryDependencies: ['product-card'],
    files: ['primitives/products-list/index.tsx', 'primitives/products-list/compare-drawer.tsx'],
  },
  {
    name: 'rating',
    dependencies: [],
    registryDependencies: [],
    files: ['primitives/rating/index.tsx'],
  },
  {
    name: 'select',
    dependencies: ['@radix-ui/react-select','clsx','lucid-react'],
    registryDependencies: [],
    files: ['primitives/select/index.tsx'],
  },
  {
    name: 'side-panel',
    dependencies: ['@radix-ui/react-dialog','clsx','lucid-react'],
    registryDependencies: [],
    files: ['primitives/side-panel/index.tsx'],
  },
  {
    name: 'spinner',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/spinner/index.tsx'],
  },
  {
    name: 'textarea',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/textarea/index.tsx'],
  },
  {
    name: 'toaster',
    dependencies: ['sonner'],
    registryDependencies: [],
    files: ['primitives/toaster/index.tsx'],
  },
] satisfies Components;
