import { Components } from '@/vibes/schema';

export const primitives = [
  {
    name: 'accordion',
    dependencies: ['clsx', '@radix-ui/react-accordion'],
    registryDependencies: [],
    files: ['primitives/accordion/index.tsx'],
  },
  {
    name: 'alert',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/alert/index.tsx'],
  },
  {
    name: 'animated-link',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/animated-link/index.tsx'],
  },
  {
    name: 'badge',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/badge/index.tsx'],
  },
  {
    name: 'banner',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/banner/index.tsx'],
  },
  {
    name: 'blog-post-card',
    dependencies: ['clsx'],
    registryDependencies: ['skeleton'],
    files: ['primitives/blog-post-card/index.tsx'],
  },
  {
    name: 'button',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['primitives/button/index.tsx'],
  },
  {
    name: 'button-radio-group',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/button-radio-group/index.tsx'],
  },
  {
    name: 'button-link',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/button-link/index.tsx'],
  },
  {
    name: 'calendar',
    dependencies: ['clsx', 'lucide-react', 'react-day-picker'],
    registryDependencies: [],
    files: ['primitives/calendar/index.tsx'],
  },
  {
    name: 'card-radio-group',
    dependencies: ['clsx', '@radix-ui/react-radio-group'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/card-radio-group/index.tsx'],
  },
  {
    name: 'compare-card',
    dependencies: ['clsx'],
    registryDependencies: ['skeleton', 'product-card', 'rating', 'button'],
    files: ['primitives/compare-card/index.tsx'],
  },
  {
    name: 'compare-drawer',
    dependencies: ['@radix-ui/react-portal', 'lucide-react', 'nuqs'],
    registryDependencies: ['button'],
    files: ['primitives/compare-drawer/index.tsx'],
  },
  {
    name: 'card',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: ['skeleton'],
    files: ['primitives/card/index.tsx'],
  },
  {
    name: 'carousel',
    dependencies: ['embla-carousel-react', 'lucide-react', 'clsx'],
    registryDependencies: [],
    files: ['primitives/carousel/index.tsx'],
  },
  {
    name: 'checkbox',
    dependencies: ['@radix-ui/react-checkbox', '@radix-ui/react-label', 'lucide-react', 'clsx'],
    registryDependencies: ['field-error'],
    files: ['form/checkbox/index.tsx'],
  },
  {
    name: 'checkbox-group',
    dependencies: ['clsx'],
    registryDependencies: ['field-error', 'label', 'checkbox'],
    files: ['form/checkbox-group/index.tsx'],
  },
  {
    name: 'counter',
    dependencies: ['lucide-react', 'clsx'],
    registryDependencies: [],
    files: ['primitives/counter/index.tsx'],
  },
  {
    name: 'cursor-pagination',
    dependencies: ['lucide-react', 'nuqs', 'clsx'],
    registryDependencies: [],
    files: ['primitives/cursor-pagination/index.tsx'],
  },
  {
    name: 'date-picker',
    dependencies: ['lucide-react', '@radix-ui/react-popover'],
    registryDependencies: ['input', 'calendar'],
    files: ['form/date-picker/index.tsx'],
  },
  {
    name: 'dynamic-form',
    dependencies: ['@conform-to/react', '@conform-to/zod', 'zod'],
    registryDependencies: [
      'button',
      'button-radio-group',
      'card-radio-group',
      'checkbox',
      'checkbox-group',
      'date-picker',
      'form-status',
      'input',
      'number-input',
      'radio-group',
      'select',
      'swatch-radio-group',
      'textarea',
    ],
    files: ['form/dynamic-form/index.tsx', 'form/dynamic-form/schema.ts'],
  },
  {
    name: 'favorite',
    dependencies: ['@radix-ui/react-toggle'],
    registryDependencies: [],
    files: [
      'primitives/favorite/index.tsx',
      'primitives/favorite/heart.tsx',
      'primitives/favorite/styles.css',
    ],
  },
  {
    name: 'featured-video',
    dependencies: ['clsx'],
    registryDependencies: ['button'],
    files: ['sections/featured-video/index.tsx'],
  },
  {
    name: 'field-error',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['form/field-error/index.tsx'],
  },
  {
    name: 'form-status',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: [],
    files: ['form/form-status/index.tsx'],
  },
  {
    name: 'inline-email-form',
    dependencies: ['lucide-react', '@conform-to/react', '@conform-to/zod'],
    registryDependencies: [],
    files: ['form/form-status/index.tsx'],
  },
  {
    name: 'icon',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: ['skeleton'],
    files: ['primitives/icon/index.tsx'],
  },
  {
    name: 'input',
    dependencies: ['clsx'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/input/index.tsx'],
  },
  {
    name: 'logo',
    dependencies: ['clsx'],
    registryDependencies: ['streamable', 'skeleton'],
    files: ['primitives/logo/index.tsx'],
  },
  {
    name: 'modal',
    dependencies: ['@radix-ui/react-dialog', 'clsx'],
    registryDependencies: [],
    files: ['primitives/modal/index.tsx'],
  },
  {
    name: 'number-input',
    dependencies: ['clsx', 'lucide-react'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/number-input/index.tsx'],
  },
  {
    name: 'offset-pagination',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/offset-pagination/index.tsx'],
  },
  {
    name: 'logo',
    dependencies: ['clsx'],
    registryDependencies: ['streamable'],
    files: ['primitives/logo/index.tsx'],
  },
  {
    name: 'navigation',
    dependencies: [
      '@conform-to/react',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-navigation-menu',
      '@radix-ui/react-popover',
      'clsx',
      'lodash.debounce',
      'lucide-react',
      '@conform-to/zod',
    ],
    registryDependencies: [
      'streamable',
      'button',
      'logo',
      'price-label',
      'product-card',
      'toaster',
      'form-status',
    ],
    files: ['primitives/navigation/index.tsx'],
  },
  {
    name: 'pagination',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/pagination/index.tsx'],
  },
  {
    name: 'price-label',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/price-label/index.tsx'],
  },
  {
    name: 'product-card',
    dependencies: ['clsx'],
    registryDependencies: ['badge', 'price-label', 'skeleton'],
    files: ['primitives/product-card/index.tsx', 'primitives/product-card/compare.tsx'],
  },
  {
    name: 'products-list',
    dependencies: [],
    registryDependencies: ['product-card'],
    files: ['sections/products-list/index.tsx'],
  },
  {
    name: 'radio-group',
    dependencies: ['clsx', '@radix-ui/react-radio-group'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/radio-group/index.tsx'],
  },
  {
    name: 'rating',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/rating/index.tsx'],
  },
  {
    name: 'select',
    dependencies: ['clsx', 'lucide-react', '@radix-ui/react-select'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/select/index.tsx'],
  },
  {
    name: 'side-panel',
    dependencies: ['@radix-ui/react-dialog', 'clsx', 'lucide-react'],
    registryDependencies: ['button'],
    files: ['primitives/side-panel/index.tsx'],
  },
  {
    name: 'skeleton',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/skeleton/index.tsx'],
  },
  {
    name: 'spinner',
    dependencies: ['clsx'],
    registryDependencies: [],
    files: ['primitives/spinner/index.tsx'],
  },
  {
    name: 'streamable',
    dependencies: ['uuid'],
    registryDependencies: [],
    files: ['lib/streamable.tsx'],
  },
  {
    name: 'swatch-radio-group',
    dependencies: ['clsx', 'lucide-react', '@radix-ui/react-radio-group'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/swatch-radio-group/index.tsx'],
  },
  {
    name: 'textarea',
    dependencies: ['clsx'],
    registryDependencies: ['field-error', 'label'],
    files: ['form/textarea/index.tsx'],
  },
] satisfies Components;
