import { lazy } from 'react'

import { Components } from '@/vibes/schema'

export const components = [
  {
    name: 'accordions',
    dependencies: ['@radix-ui/react-accordion'],
    registryDependencies: [],
    files: ['./components/accordions/index.tsx'],
    component: lazy(() => import('./components/accordions')),
  },
  {
    name: 'button',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/button/index.tsx'],
    component: lazy(() => import('./components/button')),
  },
  {
    name: 'card',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/card/index.tsx'],
    component: lazy(() => import('./components/card')),
  },
  {
    name: 'code-block',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/code-block/index.tsx'],
    component: lazy(() => import('./components/code-block')),
  },
  {
    name: 'copy-command',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/copy-command/index.tsx'],
    component: lazy(() => import('./components/copy-command')),
  },
  {
    name: 'feature-grid',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/feature-grid/index.tsx'],
    component: lazy(() => import('./components/feature-grid')),
  },
  {
    name: 'feed',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/feed/index.tsx'],
    component: lazy(() => import('./components/feed')),
  },
  {
    name: 'footer',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/footer/index.tsx'],
    component: lazy(() => import('./components/footer')),
  },
  {
    name: 'form',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/form/index.tsx'],
    component: lazy(() => import('./components/form')),
  },
  {
    name: 'glow-container',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/glow-container/index.tsx'],
    component: lazy(() => import('./components/glow-container')),
  },
  {
    name: 'list',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/list/index.tsx'],
    component: lazy(() => import('./components/list')),
  },
  {
    name: 'marquee',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/marquee/index.tsx'],
    component: lazy(() => import('./components/marquee')),
  },
  {
    name: 'navigation',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/navigation/index.tsx'],
    component: lazy(() => import('./components/navigation')),
  },
  {
    name: 'pricing-cards',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/pricing-cards/index.tsx'],
    component: lazy(() => import('./components/pricing-cards')),
  },
  {
    name: 'table',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/table/index.tsx'],
    component: lazy(() => import('./components/table')),
  },
  {
    name: 'tabs',
    dependencies: ['@radix-ui/react-tabs'],
    registryDependencies: [],
    files: ['./components/tabs/index.tsx'],
    component: lazy(() => import('./components/tabs')),
  },
  {
    name: 'toast',
    dependencies: [],
    registryDependencies: [],
    files: ['./components/toast/index.tsx'],
    component: lazy(() => import('./components/toast')),
  },
] satisfies Components
