import { lazy } from 'react'

import { Components } from '@/vibes/schema'

export const examples = [
  {
    name: 'accordions-example',
    dependencies: [],
    registryDependencies: ['accordions'],
    files: ['examples/accordions.tsx'],
    component: lazy(() => import('./examples/accordions')),
  },
  {
    name: 'button-example',
    dependencies: [],
    registryDependencies: ['button'],
    files: ['examples/button.tsx'],
    component: lazy(() => import('./examples/button')),
  },
  {
    name: 'card-example',
    dependencies: [],
    registryDependencies: ['card'],
    files: ['examples/card.tsx'],
    component: lazy(() => import('./examples/card')),
  },
  {
    name: 'code-block-example',
    dependencies: [],
    registryDependencies: ['code-block'],
    files: ['examples/code-block.tsx'],
    component: lazy(() => import('./examples/code-block')),
  },
  {
    name: 'copy-command-example',
    dependencies: [],
    registryDependencies: ['copy-command'],
    files: ['examples/copy-command.tsx'],
    component: lazy(() => import('./examples/copy-command')),
  },
  {
    name: 'feature-grid-example',
    dependencies: [],
    registryDependencies: ['feature-grid'],
    files: ['examples/feature-grid.tsx'],
    component: lazy(() => import('./examples/feature-grid')),
  },
  {
    name: 'feed-example',
    dependencies: [],
    registryDependencies: ['feed'],
    files: ['examples/feed.tsx'],
    component: lazy(() => import('./examples/feed')),
  },
  {
    name: 'footer-example',
    dependencies: [],
    registryDependencies: ['footer'],
    files: ['examples/footer.tsx'],
    component: lazy(() => import('./examples/footer')),
  },
  {
    name: 'form-example',
    dependencies: [],
    registryDependencies: ['form'],
    files: ['examples/form.tsx'],
    component: lazy(() => import('./examples/form')),
  },
  {
    name: 'glow-container-example',
    dependencies: [],
    registryDependencies: ['glow-container'],
    files: ['examples/glow-container.tsx'],
    component: lazy(() => import('./examples/glow-container')),
  },
  {
    name: 'list-example',
    dependencies: [],
    registryDependencies: ['list'],
    files: ['examples/list.tsx'],
    component: lazy(() => import('./examples/list')),
  },
  {
    name: 'marquee-example',
    dependencies: [],
    registryDependencies: ['marquee'],
    files: ['examples/marquee.tsx'],
    component: lazy(() => import('./examples/marquee')),
  },
  {
    name: 'navigation-example',
    dependencies: [],
    registryDependencies: ['navigation'],
    files: ['examples/navigation.tsx'],
    component: lazy(() => import('./examples/navigation')),
  },
  {
    name: 'pricing-cards-example',
    dependencies: [],
    registryDependencies: ['pricing-cards'],
    files: ['examples/pricing-cards.tsx'],
    component: lazy(() => import('./examples/pricing-cards')),
  },
  {
    name: 'table-example',
    dependencies: [],
    registryDependencies: ['table'],
    files: ['examples/table.tsx'],
    component: lazy(() => import('./examples/table')),
  },
  {
    name: 'tabs-example',
    dependencies: [],
    registryDependencies: ['tabs'],
    files: ['examples/tabs.tsx'],
    component: lazy(() => import('./examples/tabs')),
  },
  {
    name: 'video-example',
    dependencies: [],
    registryDependencies: ['video'],
    files: ['examples/video.tsx'],
    component: lazy(() => import('./examples/video')),
  },
] satisfies Components
